spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    #driver-class-name: com.mysql.jdbc.Driver
server:
  port: 80
mybatis-plus:
  type-aliases-package: com.boxi.demo.*.entity
  mapper-locations: classpath:com/boxi/demo/*/mapper/xml/*Mapper.xml